### ISSUE TITLE
Remove the need for mk and rm

### ISSUE THREAD

**Issue by adamghill** [scrummyin/django-brancher#2]
I think you could create the branch as needed and clean up when needed. Although, I wonder if it would be useful to keep the branch database around in some instances, too?

**Comment by scrummyin** [comment]
I think I'll be able to add a --isolation --migrate to the branch_it command. It will manage the life-cycle of the database, as well as run migrate before starting you application.

**Comment by scrummyin** [comment]
Complete and in production on branch_it you can pass --isolate and/or --migrate to the command and it will run in insolation. However, it will currently error if the database already exists.
